version: "3"

services:
    2022-01-26-metric-metar-for-discord:
        container_name: "2022-01-26-Metric-METAR-for-Discord"
        image: "9-fs/2022-01-26-metric-metar-for-discord:latest"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            DISCORD_BOT_CHANNEL_NAME: ""
            DISCORD_BOT_TOKEN: ""
        volumes:
            - "/mnt/user/appdata/2022-01-26-metric-metar-for-discord/config/:/app/config/:rw"
            - "/mnt/user/appdata/2022-01-26-metric-metar-for-discord/database/:/app/database/:rw"
            - "/mnt/user/appdata/2022-01-26-metric-metar-for-discord/log/:/app/log/:rw"
        network_mode: "bridge"
        deploy:
            resources:
                limits:
                    memory: "1G"
        user: "99:100"

networks: {}